# Twist_mux parameters

#Twist-mux combines the various navigation and movement controls sources,
#such as manual control from keyboard joystick and autonomous control from nav2
#and outputs a unified movement instruction on the /cmd_vel topic as a TwistStamped message.
#Each input source is assigned a priority so that lower level commands are ignored, such as manual override of autonomous navigation.

# For each topic:
# - name    : name identifier to select the topic (*sub-namespace, see below)
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

twist_mux:
  ros__parameters:
    use_sim_time: true
    use_stamped: true
    topics:
#      collision: #Move this to below keyboard for physical bot.
#        topic   : cmd_vel_collision #Takes input from the collision avoidance node.
#        timeout : 0.5
#        priority: 100 #Highest priority for testing.
    
      keyboard:
        topic   : cmd_vel_keyboard #Takes input directly from the command line.
        timeout : 0.5
        priority: 90 #Highest priority because it is the most direct and fail-safe.

#      joystick: #Not implement yet.
#        topic   : cmd_vel_joy #Takes input from a joystick controller, which hasnt been set up yet
#        timeout : 0.5
#        priority: 90 #High priority to override automation

      navigation:
        topic   : /demo/cmd_vel_nav #Takes input from Nav2 autonomous navigation stack.
        timeout : 0.5
        priority: 80 #This will be the main operating mode.

      docking:
        topic   : /cmd_vel_docking #Takes input from Nav2 autonomous docking stack.
        timeout : 0.5
        priority: 70 #Used only for docking. Priority doesnt matter much, I don't think, because nav2 handles the control transfer internally.
        

      tracker: #Isnt this part of nav2? Why is it separate?
        topic   : cmd_vel_tracker #Takes input from a tracking node, such as person or object tracking. Not sure why it's not part of Nav2?
        timeout : 0.5
        priority: 60 #Lowest priority so that it is easily overridden by assited_teleop or joystick control.

